src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.7/targets/mediatek/mt7622/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_cortex-a53/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.7/targets/mediatek/mt7622/kmods/6.6.141-1-2fd6ebba7d164236be638018bd983b8a
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_cortex-a53/telephony
