./.git/description
./.git/HEAD
./.git/config
./.git/FETCH_HEAD
./.git/COMMIT_EDITMSG
./.git/index
./.git/ORIG_HEAD
./.gitignore
./CONTRIBUTING.md
./README.md
./LICENSE.sh
./SH/AWK.awk
./SH/BASH.sh
./SH/ConfBashDebRpm.sh
./SH/ConfGit.sh
./SH/ConfTermux.list.sh
./SH/D
./SH/Format_t.pl
./SH/Function-Perl.md
./SH/KEYWORD_PERL.pm
./SH/PERL.pm
./SH/R
./SH/SED.sed
./SH/SSHClient.sh
./SH/SearchCp.sh
./SH/TestOpenssl.sh
./SH/README.md
./SH/Base6.pl
./SH/journal.ods
./LICENSE
./CHANGELOG
./.gitlab-ci.yml
