./.git/description
./.git/HEAD
./.git/config
./.git/COMMIT_EDITMSG
./.git/index
./.git/FETCH_HEAD
./.git/ORIG_HEAD
./CHANGELOG
./Generate.stat
./Init.sh
./LICENSE
./Locate.stat
./README.md
./SH/AWK.awk
./SH/BASH.sh
./SH/Base6.pl
./SH/ConfDeb.sh
./SH/ConfGit.sh
./SH/ConfTermux.sh
./SH/Format_t.pl
./SH/Function-Perl.md
./SH/PERL.pm
./SH/README.md
./SH/SED.sed
./SH/SSHCli.sh
./SH/SearchCp.sh
./SH/TestOpenssl.sh
./SH/UEncrypt.pl
./SH/journal.ods
./SH/GREP.bash
./openwrt.list
./ca-iptables
./openssl.md
./vm-openwrt.sh
./rules/cr660x.mtd
./rules/key
./rules/appent.ip
./rules/delete.ip
./rules/x.dic
./rules/z.dic
./rules/cmcc_rax3000m.mtd
./rules/drop.list
./rules/fu.l
./rules/restore.sh
./rules/rules.v4
./rules/rules.v6
./rules/test.iptables
./rules/v4.iptables
./speedtest.bash
./atob.bash
./usb.wifi
./grub.cfg
./hostapd.conf
./gentoo.config.nou
