#!/bin/sh
touch /root/.vimrc
i41p='i41p'
i61p='i61p'
m1m='m1m'
tables='fw4'
a="export PS1='\[\e[1;95m\]\W \[\e[1;33m\]\\$ \[\e[0m\]'"
st2=$(dd if=/dev/urandom bs=1 count=1|hexdump -e '1 "%01x"')
st4=$(dd if=/dev/urandom bs=2 count=1|hexdump -e '1 "%04x"')
r16r=$((16+$RANDOM%16))
r255r=$((RANDOM%255))
if $(uci get network.lan.ipaddr | grep -q '/');then
	uci set network.lan.ipaddr="172.${r16r}.${r255r}.1/24"
else
	uci set network.lan.ipaddr="172.${r16r}.${r255r}.1"
fi
nip=$(uci get network.lan.ipaddr|awk -F '/' '{print $1}')
uci commit
if [ -d "/etc/profile.d/" ] ; then
	echo ${a} > /etc/profile.d/z99.sh
else
	mkdir /etc/profile.d
	echo ${a} > /etc/profile.d/z99.sh
fi
unset a
cat > /root/hts.sh << 'GHTTPS'
openssl ecparam -name prime256v1 -out /etc/ecparam.pem
openssl req -new -newkey ec:/etc/ecparam.pem -days 555 -nodes -x509 -keyout /etc/uhttpd.key -out /etc/uhttpd.crt -subj "/C=CN/ST=st/L=l/O=o/OU=ou/CN=cn/emailAddress=email@emil.com"
openssl ecparam -name prime256v1 -out /etc/radius/ecparam.pem
openssl req -new -newkey ec:/etc/radius/ecparam.pem -days 555 -nodes -x509 -keyout /etc/radius/key.pem -out /etc/radius/cert.pem -subj "/C=CN/ST=st/L=l/O=o/OU=ou/CN=cn/emailAddress=email@emil.com"
openssl req -new -newkey ec:/etc/ecparam.pem -nodes -keyout /etc/radius/server.key -out /etc/radius/server.csr -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=cn"
openssl x509 -req -in /etc/radius/server.csr -CA /etc/radius/cert.pem -CAkey /etc/radius/key.pem -CAcreateserial -out /etc/radius/ca.pem -days 555
uci batch << WW
delete uhttpd.main.listen_http
del_list uhttpd.main.listen_https='[::]:443'
delete uhttpd.defaults
set uhttpd.main.redirect_https='0'
set uhttpd.main.max_connections='1'
delete dhcp.@dnsmasq[0].boguspriv
delete dhcp.@dnsmasq[0].filterwin2k
delete dhcp.@dnsmasq[0].nonegcache
delete dhcp.@dnsmasq[0].nonwildcard
set dhcp.@dnsmasq[0].sequential_ip='1'
set dhcp.@dnsmasq[0].interface='lan'
commit
WW
# echo -e '# fq fq_codel\nnet.core.default_qdisc = fq_codel\n# hybla bbr\nnet.ipv4.tcp_congestion_control = bbr' >> /etc/sysctl.conf
# sysctl -p
ssh-keygen -t ed25519
cp /etc/dropbear/authorized_keys /root/.ssh
rm $0
GHTTPS

cat > /root/nft.init.0 << EXO
#!/bin/sh
set -e
set -o pipefail
case "\$1" in
	i4 )
		nft add element inet ${tables} ${i41p} {"\$2"}
		;;
	i6 )
		nft add element inet ${tables} ${i61p} {"\$2"}
		;;
	im )
		nft add element inet ${tables} ${m1m} {"\$2"}
		;;
	i4d )
		nft delete element inet ${tables} ${i41p} {"\$2"}
		;;
	i6d )
		nft delete element inet ${tables} ${i61p} {"\$2"}
		;;
	imd )
		nft delete element inet ${tables} ${m1m} {"\$2"}
		;;
	is )
		nft list set inet ${tables} ${i41p} | sed '1d;\$d' > /etc/nftables.d/i41p
		nft list set inet ${tables} ${i61p} | sed '1d;\$d' > /etc/nftables.d/i61p
		;;
	m )
		nft list set inet ${tables} ${m1m} | sed '1d;\$d' > /etc/nftables.d/m1m
		;;
esac
EXO

rm /etc/uci-defaults/99-asu-defaults
touch /etc/dropbear/authorized_keys
pd="fe80::${nip}"
(echo ${pd};sleep 1;echo ${pd}) | passwd > /dev/null

rm /etc/nftables.d/*
echo -e "set i41p {\n\ttype ipv4_addr\n\tflags interval\n}" > /etc/nftables.d/i41p
echo -e "set i61p {\n\ttype ipv6_addr\n\tflags interval\n}" > /etc/nftables.d/i61p
echo -e "set m1m {\n\ttype ether_addr\n\tflags interval\n}" > /etc/nftables.d/m1m

cat > /etc/nftables.d/u.nft << NFTC
include "/etc/nftables.d/i41p"
include "/etc/nftables.d/i61p"
include "/etc/nftables.d/m1m"
chain upi {
	type filter hook input priority -1; policy accept;
	ip saddr @${i41p} drop
	ip6 saddr @${i61p} drop
	ether saddr @${m1m} drop
}

chain upf {
	type filter hook forward priority -1; policy accept;
	ip daddr @${i41p} drop comment "drop ct state all"
	ip6 daddr @${i61p} drop
#	ip daddr {192.168.0.3} tcp dport {80,443} drop comment "drop ct state all"
#	ip daddr {192.168.0.3} tcp dport 22 limit rate 10/second log prefix "--- "
	ether saddr @${m1m} drop
}

chain upo {
	type filter hook output priority -1; policy accept;
}

chain udn {
	type nat hook prerouting priority dstnat; policy accept;
#	iifname "br-lan" ip daddr {192.168.1.2} tcp dport {80,443} dnat to ${nip}
}

NFTC

if $(fw_printenv|grep -q 'model=RB03') && [[ -z $(uci get wireless.radio1.path 2>/dev/null) ]];then
	uci set wireless.radio0.path='platform/18000000.wmac'
	uci set wireless.radio1.path='1a143000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	uci commit
fi
[[ $(uci get wireless.radio0.channel) = '1' ]] && {
	uci set wireless.radio0.channel=$((5+$RANDOM%5))
	uci set wireless.radio1.channel=$((153+$RANDOM%3*4))
	uci set wireless.radio0.htmode='HT40'
	uci set wireless.radio0.noscan='1'
	uci set wireless.radio1.disabled='0'
	uci set wireless.default_radio1.disabled='0'
	uci set wireless.default_radio0.disabled='1'
	uci commit
}
[[ $(uci get wireless.radio1.channel) = '1' ]] && {
	uci set wireless.radio1.channel=5
	uci set wireless.radio0.channel=153
	uci set wireless.radio1.htmode='HT40'
	uci set wireless.radio1.noscan='1'
	uci set wireless.radio0.disabled='0'
	uci set wireless.default_radio0.disabled='0'
	uci set wireless.default_radio1.disabled='1'
	uci commit
}
uci batch << EEOO
set dropbear.main.DirectInterface='lan'
set dropbear.main.Port='12345'
set network.globals.packet_steering='2'
set network.globals.tcp_l3mdev='1'
set network.globals.udp_l3mdev='1'
set network.globals.steering_flows='128'
set dhcp.odhcpd.loglevel='1' #4
set dhcp.@dnsmasq[0].domain='o'
set dhcp.@dnsmasq[0].local='/o/'
set dhcp.@dnsmasq[0].cachesize="9999"
set dhcp.@dnsmasq[0].min_cache_ttl='600'
set dhcp.@dnsmasq[0].max_cache_ttl='3000'
set dhcp.lan.leasetime='3h'
set firewall.@defaults[0].synflood_protect='1'
set firewall.@defaults[0].flow_offloading='0'
set firewall.@defaults[0].flow_offloading_hw='0'
set system.@system[0].hostname="${st2}"
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'
set system.ntp.enable_server='0'
set system.ntp.interface='lan'
add_list dhcp.lan.dhcp_option="3,${nip}"
add_list dhcp.lan.dhcp_option='6,${nip}'
set wireless.radio0.country='CN'
set wireless.radio1.country='CN'
set wireless.default_radio0.ssid="xiaomi-${st4}"
set wireless.default_radio0.encryption='psk2+ccmp'
set wireless.default_radio0.key='00001111'
set wireless.default_radio0.wpa_disable_eapol_key_retries='1'
set wireless.default_radio0.ieee80211w='2'
set wireless.default_radio0.ocv='1'
set wireless.default_radio0.multicast_to_unicast_all='1'
set wireless.default_radio0.time_advertisement='2'
set wireless.default_radio0.time_zone='CST-8'
set wireless.default_radio1.ssid="redmi-${st4}"
set wireless.default_radio1.encryption='psk2+ccmp'
set wireless.default_radio1.key='00001111'
set wireless.default_radio1.wpa_disable_eapol_key_retries='1'
set wireless.default_radio1.ieee80211w='2'
set wireless.default_radio1.ocv='1'
set wireless.default_radio1.multicast_to_unicast_all='1'
set wireless.default_radio1.time_advertisement='2'
set wireless.default_radio1.time_zone='CST-8'
commit
EEOO
if $(opkg list-installed | grep -q unbound-daemon) ; then
	uci set dhcp.@dnsmasq[0].dnssec='0'
	uci set dhcp.@dnsmasq[0].port='1025'
	uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#53'
	uci set dhcp.@dnsmasq[0].noresolv='1'
	uci set unbound.ub_main.listen_port='53'
	uci set unbound.ub_main.manual_conf='1'
	uci add_list unbound.ub_main.trigger_interface='lan'
	uci add_list unbound.ub_main.trigger_interface='wan'
	uci commit
	echo -e '\nserver=/#/127.0.0.1#53\nserver=/*.*/127.0.0.1#53' >> /etc/dnsmasq.conf
cat > /root/unbound.conf << 'UNBOUND'
#include: "otherfile.conf"
#include-toplevel: "otherfile.conf"

server:
	verbosity: 1
	statistics-interval: 28800
	shm-enable: yes
	shm-key: 11777
	# statistics-cumulative: no
	# extended-statistics: no
	statistics-inhibit-zero: yes
	num-threads: 2
	# interface: 192.0.2.153
	# interface: 192.0.2.154
	# interface: 192.0.2.154@5003
	# interface: 2001:DB8::5
	# interface: eth0@5003
	# interface-automatic: no
	# interface-automatic-ports: ""
	port: 53
	interface: 0.0.0.0
	interface: ::0
	# outgoing-interface: 192.0.2.153
	# outgoing-interface: 2001:DB8::5
	# outgoing-interface: 2001:DB8::6
	# outgoing-interface: 2001:DB8::/64
	# prefer-ip6: no
	# prefer-ip4: no
	outgoing-range: 4096
	# outgoing-port-permit: 32768
	# outgoing-port-avoid: "3200-3208"
	outgoing-num-tcp: 10
	incoming-num-tcp: 10
	so-rcvbuf: 0
	so-sndbuf: 4m
	so-reuseport: yes
	# ip-transparent: no
	# ip-freebind: no
	# ip-dscp: 0
	edns-buffer-size: 1232
	max-udp-size: 1232
	stream-wait-size: 4m
	msg-buffer-size: 65552
	msg-cache-size: 4m
	msg-cache-slabs: 4
	num-queries-per-thread: 2048
	jostle-timeout: 200
	# delay-close: 0
	udp-connect: yes
	outbound-msg-retry: 5
	max-sent-count: 32
	max-query-restarts: 11
	iter-scrub-ns: 20
	iter-scrub-cname: 11
	max-global-quota: 200
	iter-scrub-promiscuous: yes
	unknown-server-time-limit: 376
	discard-timeout: 1900
	wait-limit: 1000
	wait-limit-cookie: 10000
	wait-limit-netblock: 127.0.0.0/8 -1
	wait-limit-netblock: ::1/128 -1
	wait-limit-cookie-netblock: 127.0.0.0/8 -1
	wait-limit-cookie-netblock: ::1/128 -1
	rrset-cache-size: 4m
	rrset-cache-slabs: 4
	cache-min-ttl: 3600
	cache-max-ttl: 86400
	# cache-max-negative-ttl: 3600
	# cache-min-negative-ttl: 0
	# infra-host-ttl: 900
	# infra-cache-min-rtt: 50
	# infra-cache-max-rtt: 120000
	# infra-keep-probing: no
	# infra-cache-slabs: 4
	# infra-cache-numhosts: 10000
	# define-tag: "tag1 tag2 tag3"
	do-ip4: yes
	do-ip6: yes
	# do-nat64: no
	# nat64-prefix: 64:ff9b::0/96
	do-udp: yes
	do-tcp: yes
	# tcp-upstream: no
	# udp-upstream-without-downstream: no
	# tcp-mss: 0
	# outgoing-tcp-mss: 0
	# tcp-idle-timeout: 30000
	# edns-tcp-keepalive: no
	# edns-tcp-keepalive-timeout: 120000
	# sock-queue-timeout: 0
	# use-systemd: no
	# do-daemonize: yes
	access-control: 127.0.0.0/8 allow
	access-control: ::1 allow
	access-control: ::ffff:127.0.0.1 allow
	access-control: 172.16.0.0/12 allow
	# access-control: 192.168.0.0/16 allow
	# access-control: 10.0.0.0/8 allow
	# access-control-tag: 192.0.2.0/24 "tag2 tag3"
	# access-control-tag-action: 192.0.2.0/24 tag3 refuse
	# access-control-tag-data: 192.0.2.0/24 tag2 "A 127.0.0.1"
	# access-control-view: 192.0.2.0/24 viewname
	# interface-action: 192.0.2.153 allow
	# interface-action: 192.0.2.154 allow
	# interface-action: 192.0.2.154@5003 allow
	# interface-action: 2001:DB8::5 allow
	# interface-action: eth0@5003 allow
	# interface-tag: eth0@5003 "tag2 tag3"
	# interface-tag-action: eth0@5003 tag3 refuse
	# interface-tag-data: eth0@5003 tag2 "A 127.0.0.1"
	# interface-view: eth0@5003 viewname
	# chroot: "/var/lib/unbound"
	# username: "unbound"
	# directory: "/var/lib/unbound"
	# logfile: ""
	# use-syslog: yes
	# log-identity: ""
	# log-time-ascii: no
	# log-time-iso: no
	# log-queries: no
	# log-replies: no
	# log-tag-queryreply: no
	# log-destaddr: no
	# log-local-actions: no
	# log-servfail: no
	# pidfile: "/var/run/unbound.pid"
	# root-hints: ""
	# hide-identity: no
	# hide-version: no
	# hide-trustanchor: no
	# hide-http-user-agent: no
	# identity: ""
	# version: ""
	# nsid: ""
	# http-user-agent: ""
	target-fetch-policy: "3 2 1 0 0"
	harden-short-bufsize: yes
	harden-large-queries: yes
	harden-glue: yes
	# harden-unverified-glue: no
	harden-dnssec-stripped: yes
	harden-below-nxdomain: yes
	harden-referral-path: yes
	harden-algo-downgrade: yes
	harden-unknown-additional: yes
	qname-minimisation: yes
	qname-minimisation-strict: yes
	aggressive-nsec: yes
	use-caps-for-id: yes
	# caps-exempt: "licdn.com"
	# caps-exempt: "senderbase.org"
	# private-address: 10.0.0.0/8
	private-address: 172.16.0.0/12
	# private-address: 192.168.0.0/16
	# private-address: 169.254.0.0/16
	private-address: fd00::/8
	private-address: fe80::/10
	private-address: ::ffff:0:0/96
	# private-domain: "example.com"
	# unwanted-reply-threshold: 0
	# do-not-query-address: 127.0.0.1/8
	# do-not-query-address: ::1
	# do-not-query-localhost: yes
	# prefetch: no
	# prefetch-key: no
	# deny-any: no
	rrset-roundrobin: yes
	minimal-responses: yes
	# disable-dnssec-lame-check: no
	module-config: "iterator"
	auto-trust-anchor-file: "/var/lib/unbound/root.key"
	# trust-anchor-signaling: yes
	# root-key-sentinel: yes
	# trust-anchor-file: ""
	# trusted-keys-file: ""
	# domain-insecure: "example.com"
	# val-override-date: ""
	# val-bogus-ttl: 60
	# val-sig-skew-min: 3600
	# val-sig-skew-max: 86400
	# val-max-restart: 5
	# val-clean-additional: yes
	# val-permissive-mode: no
	# ignore-cd-flag: no
	# disable-edns-do: no
	# serve-expired: no
	# serve-expired-ttl: 86400
	# serve-expired-ttl-reset: no
	# serve-expired-reply-ttl: 30
	# serve-expired-client-timeout: 1800
	# serve-original-ttl: no
	# val-log-level: 0
	# val-nsec3-keysize-iterations: "1024 150 2048 150 4096 150"
	# zonemd-permissive-mode: no
	# add-holddown: 2592000 # 30 days
	# del-holddown: 2592000 # 30 days
	# keep-missing: 31622400 # 366 days
	# permit-small-holddown: no
	key-cache-size: 4m
	key-cache-slabs: 4
	neg-cache-size: 1m
	trust-anchor: "nlnetlabs.nl. DNSKEY 257 3 5 AQPzzTWMz8qSWIQlfRnPckx2BiVmkVN6LPupO3mbz7FhLSnm26n6iG9N Lby97Ji453aWZY3M5/xJBSOS2vWtco2t8C0+xeO1bc/d6ZTy32DHchpW 6rDH1vp86Ll+ha0tmwyy9QP7y2bVw5zSbFCrefk8qCUBgfHm9bHzMG1U BYtEIQ=="
	trust-anchor: "jelte.nlnetlabs.nl. DS 42860 5 1 14D739EB566D2B1A5E216A0BA4D17FA9B038BE4A"
	local-zone: "localhost." nodefault
	local-zone: "127.in-addr.arpa." nodefault
	local-zone: "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa." nodefault
	local-zone: "home.arpa." nodefault
	local-zone: "resolver.arpa." nodefault
	local-zone: "service.arpa." nodefault
	local-zone: "onion." nodefault
	local-zone: "test." nodefault
	local-zone: "invalid." nodefault
	local-zone: "10.in-addr.arpa." nodefault
	local-zone: "16.172.in-addr.arpa." nodefault
	local-zone: "17.172.in-addr.arpa." nodefault
	local-zone: "18.172.in-addr.arpa." nodefault
	local-zone: "19.172.in-addr.arpa." nodefault
	local-zone: "20.172.in-addr.arpa." nodefault
	local-zone: "21.172.in-addr.arpa." nodefault
	local-zone: "22.172.in-addr.arpa." nodefault
	local-zone: "23.172.in-addr.arpa." nodefault
	local-zone: "24.172.in-addr.arpa." nodefault
	local-zone: "25.172.in-addr.arpa." nodefault
	local-zone: "26.172.in-addr.arpa." nodefault
	local-zone: "27.172.in-addr.arpa." nodefault
	local-zone: "28.172.in-addr.arpa." nodefault
	local-zone: "29.172.in-addr.arpa." nodefault
	local-zone: "30.172.in-addr.arpa." nodefault
	local-zone: "31.172.in-addr.arpa." nodefault
	local-zone: "168.192.in-addr.arpa." nodefault
	local-zone: "0.in-addr.arpa." nodefault
	local-zone: "254.169.in-addr.arpa." nodefault
	local-zone: "2.0.192.in-addr.arpa." nodefault
	local-zone: "100.51.198.in-addr.arpa." nodefault
	local-zone: "113.0.203.in-addr.arpa." nodefault
	local-zone: "255.255.255.255.in-addr.arpa." nodefault
	local-zone: "0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa." nodefault
	local-zone: "d.f.ip6.arpa." nodefault
	local-zone: "8.e.f.ip6.arpa." nodefault
	local-zone: "9.e.f.ip6.arpa." nodefault
	local-zone: "a.e.f.ip6.arpa." nodefault
	local-zone: "b.e.f.ip6.arpa." nodefault
	local-zone: "8.b.d.0.1.0.0.2.ip6.arpa." nodefault
	# local-zone: "example.com" ipset
	# unblock-lan-zones: no
	# insecure-lan-zones: no
	#       local-zone: <zone> <type>
	#       local-data: "<resource record string>"
	# local-zone: "local." static
	# local-data: "mycomputer.local. IN A 192.0.2.51"
	# local-data: 'mytext.local TXT "content of text record"'
	# local-data: "adserver.example.com A 127.0.0.1"
	# local-zone: "example.com" redirect
	# local-data: "example.com A 192.0.2.3"
	# local-data-ptr: "192.0.2.3 www.example.com"
	# local-zone-tag: "example.com" "tag2 tag3"
	# local-zone-override: "example.com" 192.0.2.0/24 refuse
	# tls-service-key: "path/to/privatekeyfile.key"
	# tls-service-pem: "path/to/publiccertfile.pem"
	# tls-port: 853
	# https-port: 443
	# quic-port: 853
	# tls-ciphers: "DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256"
	# tls-ciphersuites: "TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
	# pad-responses: yes
	# pad-responses-block-size: 468
	# tls-use-sni: yes
	# tls-session-ticket-keys: "path/to/secret_file1"
	# tls-session-ticket-keys: "path/to/secret_file2"
	# tls-upstream: no
	# tls-cert-bundle: ""
	# tls-win-cert: no
	# tls-system-cert: no
	# pad-queries: yes
	# pad-queries-block-size: 128
	# http-endpoint: "/dns-query"
	# http-max-streams: 100
	# http-query-buffer-size: 4m
	# http-response-buffer-size: 4m
	# http-nodelay: yes
	# http-notls-downstream: no
	# quic-size: 8m
	# dns64-prefix: 64:ff9b::0/96
	# dns64-ignore-aaaa: "example.com"
	# ratelimit: 0
	# ratelimit-size: 4m
	# ratelimit-slabs: 4
	# ratelimit-factor: 10
	# ratelimit-backoff: no
	# ratelimit-for-domain: example.com 1000
	# ratelimit-below-domain: com 1000
	# ip-ratelimit: 0
	# ip-ratelimit-cookie: 0
	# ip-ratelimit-size: 4m
	# ip-ratelimit-slabs: 4
	# ip-ratelimit-factor: 10
	# ip-ratelimit-backoff: no
	# tcp-connection-limit: 192.0.2.0/24 12
	# fast-server-permil: 0
	# fast-server-num: 3
	# answer-cookie: no
	# cookie-secret-file: "/usr/local/etc/unbound_cookiesecrets.txt"
	# ede: no
	# ede-serve-expired: no
	# dns-error-reporting: no
	# ipsecmod-enabled: yes
	# ipsecmod-hook: "./my_executable"
	# ipsecmod-strict: no
	# ipsecmod-max-ttl: 3600
	# ipsecmod-ignore-bogus: no
	# ipsecmod-allow: "example.com"
	# ipsecmod-allow: "nlnetlabs.nl"
	# tcp-reuse-timeout: 60000
	# max-reuse-tcp-queries: 200
	# tcp-auth-query-timeout: 3000

forward-zone:
	name: "."
	forward-addr: 114.114.114.114
	forward-addr: 223.5.5.5
	forward-addr: 1.2.4.8
	forward-first: no
	forward-tcp-upstream: no
	forward-tls-upstream: no
	forward-no-cache: no
# forward-zone:
#	name: "example.org"
#	forward-host: fwd.example.com
UNBOUND
fi
# verx=$(cat /etc/openwrt_version|awk -F '-' '{print $1}'|grep -Eo "[0-9]{5}")
# if [ "${verx}" -ge "32353" ] ;then
# fi
exit 0 
